name: Run bot

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Python
        run: |
          pip install --upgrade pip
          python3.9 -m venv env
          source env/bin/activate
          pip install discord.py
      - name: Run bot
        run: python3.9 main.py
